stages:
  - lint
  - build
  - test

image: dtreshy/go-grpc:1.20.2-mk1

lint:
  stage: lint
  script:
    - task lint

go_mod_check:
  stage: lint
  script:
    - go mod tidy -v
    - git diff --exit-code -- go.mod go.sum

build:
  stage: build
  script:
    - task build

test:
  stage: test
  script:
    - task test
    