stages:
  - lint
  - build
  - test

image: dtreshy/go-grpc:1.21.5-mk1

lint:
  stage: lint
  only:
    - merge_requests
  script:
    - task lint

go_mod_check:
  stage: lint
  only:
    - merge_requests
  script:
    - go mod tidy -v
    - git diff --exit-code -- go.mod go.sum

build:
  stage: build
  only:
    - merge_requests
  script:
    - task build
  artifacts:
    paths:
      - ./bin/sup


test:
  stage: test
  only:
    - merge_requests
  script:
    - task test

integration:
  stage: test
  only:
    - merge_requests
  needs:
    - build
  script:
    - task integration
    