stages:
  - lint
  - build
  - test

image: dtreshy/go-grpc:1.20.1-mk1

lint:
  stage: lint
  script:
    - task lint

build:
  stage: build
  script:
    - task build
  artifacts:
    paths:
      - ./bin/sup

test:
  stage: test
  script:
    - task test

integration:
  stage: test
  needs:
    - build
  script:
    - task integration
    