# https://taskfile.dev

version: '3'

tasks:
  lint:
    desc: runs golangci-lint linter
    cmds:
      - golangci-lint run --timeout 5m ./...
    silent: true

  build:
    desc: builds sup binary
    cmds:
      - go build -o ./bin/sup ./cmd/sup
    silent: true
  
  test:
    desc: runs all tests
    cmds:
      - go test ./...
    silent: true
  