# https://taskfile.dev

version: '3'

tasks:
  lint:
    desc: runs golangci-lint linter
    cmds:
      - golangci-lint run --timeout 5m ./...
    silent: true

  build:
    desc: builds sup binary
    cmds:
      - go build -o ./bin/sup ./cmd/sup
    silent: true
  
  test:
    desc: runs all tests
    cmds:
      - go test $(go list ./... | grep -v ./integration) -race -coverprofile=coverage.out -timeout 2m
    silent: true
    
  integration:
    desc: runs integration tests
    cmds:
      - go test ./integration
    silent: true
  